name: CI

on: [push,pull_request]

jobs:
  lint:
    name: Module PSSA Linting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Lint with PSSA
      uses: devblackops/github-action-psscriptanalyzer@master
      with:
        sendComment: true
        failOnErrors: true
        failOnWarnings: true
        failOnInfos: true