name: CI

on: [push]

jobs:
  lint:
    name: Run PSSA
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: lint
      uses: devblackops/github-action-psscriptanalyzer@master
      with:
        sendComment: true
